# Generated by Django 4.0.5 on 2022-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0014_alter_calc_count_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.IntegerField(null=True)),
                ('Hight', models.IntegerField(null=True)),
                ('Count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
