# Generated by Django 4.0.5 on 2022-06-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Format', models.CharField(max_length=200, null=True)),
                ('Size', models.CharField(max_length=200, null=True)),
                ('dm2', models.CharField(max_length=200, null=True)),
                ('Tray', models.CharField(max_length=200, null=True)),
                ('Lid', models.CharField(max_length=200, null=True)),
                ('Content', models.CharField(max_length=200, null=True)),
                ('Close_fitting', models.CharField(max_length=200, null=True)),
                ('Scotch', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
