# Generated by Django 4.0.5 on 2022-06-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='dm2',
        ),
        migrations.AddField(
            model_name='work',
            name='dc2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
