# Generated by Django 4.0.5 on 2022-06-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0002_remove_work_dm2_work_dc2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='dc2',
            new_name='dm2',
        ),
    ]
