# Generated by Django 4.0.5 on 2022-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0003_rename_dc2_work_dm2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('prise', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
