# Generated by Django 4.0.5 on 2022-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0004_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='size',
            new_name='size_x',
        ),
        migrations.AddField(
            model_name='material',
            name='size_y',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
