# Generated by Django 4.0.5 on 2022-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0005_rename_size_material_size_x_material_size_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='prise',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='size_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='size_y',
            field=models.FloatField(null=True),
        ),
    ]
