# Generated by Django 4.0.5 on 2022-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0007_alter_material_prise_alter_material_size_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='currency',
            field=models.IntegerField(null=True),
        ),
    ]
