# Generated by Django 4.0.5 on 2022-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0009_rename_name_material_mt_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject', models.IntegerField(null=True)),
                ('cut', models.IntegerField(null=True)),
                ('not_production', models.IntegerField(null=True)),
                ('margin', models.IntegerField(null=True)),
            ],
        ),
    ]
