# Generated by Django 4.0.5 on 2022-06-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0010_calc_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='currency',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
