# Generated by Django 4.0.5 on 2022-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0011_alter_material_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc_count',
            name='manager_proc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calc_count',
            name='style_work',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
