# Generated by Django 4.0.5 on 2022-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0012_calc_count_manager_proc_calc_count_style_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='len',
            field=models.IntegerField(null=True),
        ),
    ]
